-- Migration: Add scope_analysis column to flashcards table
-- Date: 2025-12-15
-- Description: Adds a new TEXT column to store etymology/grammar analysis from Scope and Translate feature

-- Add the scope_analysis column
ALTER TABLE flashcards 
ADD COLUMN scope_analysis TEXT;

-- Optional: Add a comment to document the column
COMMENT ON COLUMN flashcards.scope_analysis IS 'Stores etymology for words/idioms or grammar explanation for sentences, generated by Scope and Translate feature';
